async function generateReadme(prompt) {

    return `# Project README

Generated by Pitcher

## Description
Auto generated README

## Features
- Feature 1
- Feature 2

## Installation
npm install

## Usage
npm start
`;
}

module.exports = {
    generateReadme
};