function generateReadme(project) {
    const now = new Date();

    // Date Format: DD / MM / YYYY
    const date =
        String(now.getDate()).padStart(2, '0') +
        ' / ' +
        String(now.getMonth() + 1).padStart(2, '0') +
        ' / ' +
        now.getFullYear();

    const time =
        now.toLocaleTimeString(
            'en-US',
            {
                hour: '2-digit',
                minute: '2-digit',
                hour12: true
            }
        );

    const techStack = project.techStack && project.techStack.length > 0
        ? project.techStack.map(tech => `- ${tech}`).join('\n')
        : '- Not detected';

    const folderTree = project.structure ? project.structure.join('\n') : '';

    return `# ${project.projectName}

## Overview

${project.projectName} is a ${project.projectType} documented automatically by Pitcher.

---

## Project Information

| Property | Value |
|----------|--------|
| Project Name | ${project.projectName} |
| Project Type | ${project.projectType} |
| Total Folders | ${project.totalFolders || 0} |
| Total Files | ${project.totalFiles || 0} |
${project.emptyFoldersCount !== undefined ? `| Empty Folders | ${project.emptyFoldersCount} |\n` : ''}
---

## Technology Stack

${techStack}

---

## Folder Structure

\`\`\`text
${project.projectName}/
${folderTree}
\`\`\`

---

## Features

- Automatic README generation
- Automatic README updates
- Technology stack detection
- Folder structure analysis
- Project statistics

---

## Installation

Refer to project specific setup instructions.

\`\`\`bash
cd ${project.projectName}
\`\`\`

---

## Statistics

| Metric | Count |
|---------|---------|
| Total Folders | ${project.totalFolders || 0} |
| Total Files | ${project.totalFiles || 0} |
${project.emptyFoldersCount !== undefined ? `| Empty Folders | ${project.emptyFoldersCount} |\n` : ''}
---

## Author

Generated by Pitcher

**Author:** ${project.author || 'Developer'}  
Pitcher Managed  
Last Updated: ${date} at ${time}
`;
}

module.exports = {
    generateReadme
};