
function generateReadme(project) {

    const now = new Date();

    const date =
        String(now.getDate()).padStart(2, '0') +
        ' / ' +
        String(now.getMonth() + 1).padStart(2, '0') +
        ' / ' +
        now.getFullYear();

    const time =
        now.toLocaleTimeString(
            'en-US',
            {
                hour: '2-digit',
                minute: '2-digit',
                hour12: true
            }
        );

    const techStack =
        project.techStack
            .map(
                tech => `- ${tech}`
            )
            .join('\n');

    const folderTree =
        project.structure
            .join('\n');

    return `# ${project.projectName}

## Overview

${project.projectName} is a ${project.projectType} documented automatically by Pitcher.

---

## Project Information

| Property | Value |
|----------|--------|
| Project Name | ${project.projectName} |
| Project Type | ${project.projectType} |
| Total Folders | ${(project.totalFolders) - 1} |
| Total Files | ${project.totalFiles} |


---

## Technology Stack

${techStack}

---

## Folder Structure

\`\`\`text
${project.projectName}
${folderTree}
\`\`\`

---

## Features

- Automatic README generation
- Automatic README updates
- Technology stack detection
- Folder structure analysis
- Project statistics

---

## Installation

\`\`\`bash
git clone <repository-url>

cd ${project.projectName}
\`\`\`

---

## Statistics

| Metric | Count |
|---------|---------|
| Folders | ${(project.totalFolders)-1} |
| Files | ${project.totalFiles} |


---

## Author

Generated by Pitcher

Pitcher Managed
Last Updated: ${date} at ${time}
`;
}

module.exports = {
    generateReadme
};

